;COUNT NUMBER OF OCCURENCES IN THE ARRAY
;KEY IS 4 IN R4

	AREA RESET,CODE
		ENTRY
		;INITIALISATION
		LDR R0,=ARR
		MOV R1,#0 ;i
		MOV R7,#0 ;NO OF OCCURENCES
		MOV R4,#1 ;KEY
		;OPERATION
CONT 
		LDR R3,[R0]
		CMP R3,R4
		BNE SKIP
		ADD R7,R7,#1
		
SKIP
		ADD R0,#4
		ADD R1,#1
		CMP R1,#10
		BNE CONT
		
STOP	B STOP

ARR DCD 0,5,1,4,100,4,0,8,7,20
	END